- job:
    name: f34-gcc-netconf-cli-no-sysrepo
    description: |
      Build a minimal version without sysrepo or the test suite
    parent: f34-gcc

- project:
    check:
      jobs:
        - f34-gcc-cover:
            requires: CzechLight-deps-f34-gcc
        - f34-clang-asan-ubsan:
            requires: CzechLight-deps-f34-clang-asan-ubsan
        - f34-clang-tsan:
            requires: CzechLight-deps-f34-clang-tsan
        - f34-gcc-netconf-cli-no-sysrepo:
            requires: CzechLight-deps-f34-gcc
        - f34-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f34-gcc-cover-previous:
            requires: CzechLight-deps-f34-gcc
